// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type enforcerPathPatternEntry struct {
	_          structs.HostLayout
	Pattern    [64]int8
	PolicyId   uint32
	PatternLen uint8
	Pad        [3]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	enforcerMapBlockedCommandPatterns = "blocked_command_patterns"
	enforcerMapBlockedPathPatterns    = "blocked_path_patterns"
	enforcerMapBlockedPathsMap        = "blocked_paths_map"
	enforcerMapExecPath               = "exec_path"
	enforcerMapFileOpenPath           = "file_open_path"
	enforcerMapTrackedPids            = "tracked_pids"
	enforcerMapViolations             = "violations"
	enforcerProgCheckExec             = "check_exec"
	enforcerProgCheckFileOpen         = "check_file_open"
	enforcerProgCheckSocketConnect    = "check_socket_connect"
	enforcerProgCheckSocketCreate     = "check_socket_create"
	enforcerProgCheckSocketSendmsg    = "check_socket_sendmsg"
	enforcerVarAllowLocalDns          = "allow_local_dns"
	enforcerVarDnsAddrHost            = "dns_addr_host"
	enforcerVarEnforceNetwork         = "enforce_network"
	enforcerVarNetworkPolicyId        = "network_policy_id"
	enforcerVarProxyAddrHost          = "proxy_addr_host"
	enforcerVarProxyPortHost          = "proxy_port_host"
)

// loadEnforcer returns the embedded CollectionSpec for enforcer.
func loadEnforcer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EnforcerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load enforcer: %w", err)
	}

	return spec, err
}

// loadEnforcerObjects loads enforcer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*enforcerObjects
//	*enforcerPrograms
//	*enforcerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEnforcerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadEnforcer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// enforcerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerSpecs struct {
	enforcerProgramSpecs
	enforcerMapSpecs
	enforcerVariableSpecs
}

// enforcerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerProgramSpecs struct {
	CheckExec          *ebpf.ProgramSpec `ebpf:"check_exec"`
	CheckFileOpen      *ebpf.ProgramSpec `ebpf:"check_file_open"`
	CheckSocketConnect *ebpf.ProgramSpec `ebpf:"check_socket_connect"`
	CheckSocketCreate  *ebpf.ProgramSpec `ebpf:"check_socket_create"`
	CheckSocketSendmsg *ebpf.ProgramSpec `ebpf:"check_socket_sendmsg"`
}

// enforcerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerMapSpecs struct {
	BlockedCommandPatterns *ebpf.MapSpec `ebpf:"blocked_command_patterns"`
	BlockedPathPatterns    *ebpf.MapSpec `ebpf:"blocked_path_patterns"`
	BlockedPathsMap        *ebpf.MapSpec `ebpf:"blocked_paths_map"`
	ExecPath               *ebpf.MapSpec `ebpf:"exec_path"`
	FileOpenPath           *ebpf.MapSpec `ebpf:"file_open_path"`
	TrackedPids            *ebpf.MapSpec `ebpf:"tracked_pids"`
	Violations             *ebpf.MapSpec `ebpf:"violations"`
}

// enforcerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type enforcerVariableSpecs struct {
	AllowLocalDns   *ebpf.VariableSpec `ebpf:"allow_local_dns"`
	DnsAddrHost     *ebpf.VariableSpec `ebpf:"dns_addr_host"`
	EnforceNetwork  *ebpf.VariableSpec `ebpf:"enforce_network"`
	NetworkPolicyId *ebpf.VariableSpec `ebpf:"network_policy_id"`
	ProxyAddrHost   *ebpf.VariableSpec `ebpf:"proxy_addr_host"`
	ProxyPortHost   *ebpf.VariableSpec `ebpf:"proxy_port_host"`
}

// enforcerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerObjects struct {
	enforcerPrograms
	enforcerMaps
	enforcerVariables
}

func (o *enforcerObjects) Close() error {
	return _EnforcerClose(
		&o.enforcerPrograms,
		&o.enforcerMaps,
	)
}

// enforcerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerMaps struct {
	BlockedCommandPatterns *ebpf.Map `ebpf:"blocked_command_patterns"`
	BlockedPathPatterns    *ebpf.Map `ebpf:"blocked_path_patterns"`
	BlockedPathsMap        *ebpf.Map `ebpf:"blocked_paths_map"`
	ExecPath               *ebpf.Map `ebpf:"exec_path"`
	FileOpenPath           *ebpf.Map `ebpf:"file_open_path"`
	TrackedPids            *ebpf.Map `ebpf:"tracked_pids"`
	Violations             *ebpf.Map `ebpf:"violations"`
}

func (m *enforcerMaps) Close() error {
	return _EnforcerClose(
		m.BlockedCommandPatterns,
		m.BlockedPathPatterns,
		m.BlockedPathsMap,
		m.ExecPath,
		m.FileOpenPath,
		m.TrackedPids,
		m.Violations,
	)
}

// enforcerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerVariables struct {
	AllowLocalDns   *ebpf.Variable `ebpf:"allow_local_dns"`
	DnsAddrHost     *ebpf.Variable `ebpf:"dns_addr_host"`
	EnforceNetwork  *ebpf.Variable `ebpf:"enforce_network"`
	NetworkPolicyId *ebpf.Variable `ebpf:"network_policy_id"`
	ProxyAddrHost   *ebpf.Variable `ebpf:"proxy_addr_host"`
	ProxyPortHost   *ebpf.Variable `ebpf:"proxy_port_host"`
}

// enforcerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEnforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type enforcerPrograms struct {
	CheckExec          *ebpf.Program `ebpf:"check_exec"`
	CheckFileOpen      *ebpf.Program `ebpf:"check_file_open"`
	CheckSocketConnect *ebpf.Program `ebpf:"check_socket_connect"`
	CheckSocketCreate  *ebpf.Program `ebpf:"check_socket_create"`
	CheckSocketSendmsg *ebpf.Program `ebpf:"check_socket_sendmsg"`
}

func (p *enforcerPrograms) Close() error {
	return _EnforcerClose(
		p.CheckExec,
		p.CheckFileOpen,
		p.CheckSocketConnect,
		p.CheckSocketCreate,
		p.CheckSocketSendmsg,
	)
}

func _EnforcerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed enforcer_bpfeb.o
var _EnforcerBytes []byte
