// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	monitorMapEvents         = "events"
	monitorMapTrackedPids    = "tracked_pids"
	monitorProgHandleConnect = "handle_connect"
	monitorProgHandleExecve  = "handle_execve"
	monitorProgHandleExit    = "handle_exit"
	monitorProgHandleFork    = "handle_fork"
	monitorProgHandleOpenat  = "handle_openat"
)

// loadMonitor returns the embedded CollectionSpec for monitor.
func loadMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load monitor: %w", err)
	}

	return spec, err
}

// loadMonitorObjects loads monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*monitorObjects
//	*monitorPrograms
//	*monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type monitorSpecs struct {
	monitorProgramSpecs
	monitorMapSpecs
	monitorVariableSpecs
}

// monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type monitorProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
	HandleExecve  *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleExit    *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork    *ebpf.ProgramSpec `ebpf:"handle_fork"`
	HandleOpenat  *ebpf.ProgramSpec `ebpf:"handle_openat"`
}

// monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type monitorMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	TrackedPids *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type monitorVariableSpecs struct {
}

// monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type monitorObjects struct {
	monitorPrograms
	monitorMaps
	monitorVariables
}

func (o *monitorObjects) Close() error {
	return _MonitorClose(
		&o.monitorPrograms,
		&o.monitorMaps,
	)
}

// monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type monitorMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	TrackedPids *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *monitorMaps) Close() error {
	return _MonitorClose(
		m.Events,
		m.TrackedPids,
	)
}

// monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type monitorVariables struct {
}

// monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type monitorPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
	HandleExecve  *ebpf.Program `ebpf:"handle_execve"`
	HandleExit    *ebpf.Program `ebpf:"handle_exit"`
	HandleFork    *ebpf.Program `ebpf:"handle_fork"`
	HandleOpenat  *ebpf.Program `ebpf:"handle_openat"`
}

func (p *monitorPrograms) Close() error {
	return _MonitorClose(
		p.HandleConnect,
		p.HandleExecve,
		p.HandleExit,
		p.HandleFork,
		p.HandleOpenat,
	)
}

func _MonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed monitor_bpfel.o
var _MonitorBytes []byte
